#!/usr/bin/env python
# coding=utf-8

"""
Copyright (C) 2012 Martin Åberg

This program is free software: you can redistribute it and/or modify it
under the terms of the GNU General Public License as published by the Free
Software Foundation, either version 3 of the License, or (at your option)
any later version.

This program is distributed in the hope that it will be useful, but WITHOUT
ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with
this program (COPYING).  If not, see <http://www.gnu.org/licenses/>.
"""

import sys
import csv
import re
import string

reader = csv.reader(sys.stdin, delimiter=";")
target = []
for row in reader:
    limits = re.search(r"^(\d+)-?(\d+)?", row[0])
    if limits:
        entry = {}
        minmax = limits.groups()
        entry["min"] = minmax[0]
        entry["max"] = minmax[1]
        if None == entry["max"]:
            entry["max"] = entry["min"]
        description = row[1].translate(None, string.punctuation)
        description = "cc_" + description.replace(" ", "_")
        entry["name"] = description.lower()
        entry["defmin"] = description.upper() + "_MIN"
        entry["defmax"] = description.upper() + "_MAX"
        target.append(entry)

print "/* This file is automatically generated by the script"
print "cc_functions.py. */"

print
for fun in target:
    print "#define " + fun["defmin"] + " " + fun["min"]
    print "#define " + fun["defmax"] + " " + fun["max"]

print
print "static struct cc_function_node cc_functions[] = {"
for fun in target:
    print "    {.lower = " + fun["defmin"] + ","
    print "      .upper = " + fun["defmax"] + ","
    print "      .fun = " + fun["name"] + "},"
print "};"

